name: Lint
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: pnpm install --frozen-lockfile
      - name: Run ESLint
        run: pnpm lint
